name: ❄️ Lint

on: [pull_request]

jobs:
  misc:
    name: misc checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v2.4.0
      - name: spell check
        run: |
          pip install codespell==2.1.0
          git grep --cached -l '' | xargs codespell --ignore-words=.ignore_words
      - name: Merge conflict
        run: |
          grep "^<<<<<<< HEAD" $(git grep --cached -l '' | xargs) && exit 1 || true
      - name: Plugin Code
        run: |
          sudo bash ./utils/check-plugins-code.sh

  ci-eclint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out code
        uses: actions/checkout@v2.4.0

      - name: Setup Nodejs env
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '12'

      - name: Install eclint
        run: |
          sudo npm install -g eclint

      - name: Run eclint
        run: |
          eclint check
