name: ‚ùÑÔ∏è Lint

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
        node_version:
          - 14
        architecture:
          - x64
    name: Check Markdown links Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - name: Install
        run: npm install -g markdown-link-check
      - name: Run
        run: git ls-files . -m | xargs markdown-link-check -q -v  # modified files only, quiet mode, verbose mode
  markdownlint:
    name: üçá Markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: üöÄ Use Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'
      - run: npm install -g markdownlint-cli@0.25.0
      - run: markdownlint '**/*.md'
  spelling:
    name: Spell checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install
        run: |
          wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: Misspell
        run: |
          find *.md apisix doc bin t -not -path "README_ES.md" -not -path "t/toolkit/*.lua" -type f | xargs ./misspell -error
  yamllint:
    name: üç∫ YAML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'  # optional x64 or x86. Defaults to x64 if not specified
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      - name: üßπ YAML Lint
        run: |
          # return non-zero exit code on warnings
          yamllint --strict .
  trailing-whitespace:
    name: üåå Trailing whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: üßπ Check for trailing whitespace
        run: "! git grep -EIn $'[ \t]+$' | grep -v 'received: '"
